# Site settings
title: Swift
description: A clean minimal Theme for Jekyll
email: 
baseurl: /swift
url: "http://www.thelonegeek.net" # the base hostname & protocol for your site
#favicon
favicon: /favicon.png

#feed
feedburner_username: 
#twitter
twitter_username: 
github_username:  jms1989

#linkedin
linkedin_username: 

#google analytics
google_analytics_id : 
#gplus
gplus_username: 

#fb_username
fb_username: 

#permalink /blog/2014/11/11/this-is-a-sample-post
permalink: /blog/:year/:month/:day/:title
# Build settings
markdown: kramdown

#Disqus configuration
disqus_short_name: 
disqus_show_comment_count: true

#Can be used for multiple author blogs ! Add name to post For more visit the sample
authors:
  pranavrajs:
    display_name: 
    email: 
    fb: 
    linkedin: 
    twitter: 
    github: 
